{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Marine Heat Wave analysis\n",
    "The purpose of this notebook is to take in SST data, along with previously computed climatology and threshold, process these and output all the MHW events that occur in the data"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "First, we import the data and required modules. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Populating the interactive namespace from numpy and matplotlib\n"
     ]
    }
   ],
   "source": [
    "import xarray as xr\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import dask as da\n",
    "import scipy.ndimage as ndimage\n",
    "#import dask_image.ndmeasure <-- Would make computation faster - but not finished yet\n",
    "from dask.distributed import LocalCluster, Client\n",
    "%pylab inline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/distributed/dashboard/core.py:74: UserWarning: \n",
      "Port 8787 is already in use. \n",
      "Perhaps you already have a cluster running?\n",
      "Hosting the diagnostics dashboard on a random port instead.\n",
      "  warnings.warn(\"\\n\" + msg)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<table style=\"border: 2px solid white;\">\n",
       "<tr>\n",
       "<td style=\"vertical-align: top; border: 0px solid white\">\n",
       "<h3>Client</h3>\n",
       "<ul>\n",
       "  <li><b>Scheduler: </b>inproc://10.0.64.22/6973/1\n",
       "  <li><b>Dashboard: </b><a href='http://localhost:35021/status' target='_blank'>http://localhost:35021/status</a>\n",
       "</ul>\n",
       "</td>\n",
       "<td style=\"vertical-align: top; border: 0px solid white\">\n",
       "<h3>Cluster</h3>\n",
       "<ul>\n",
       "  <li><b>Workers: </b>1</li>\n",
       "  <li><b>Cores: </b>8</li>\n",
       "  <li><b>Memory: </b>33.67 GB</li>\n",
       "</ul>\n",
       "</td>\n",
       "</tr>\n",
       "</table>"
      ],
      "text/plain": [
       "<Client: scheduler='inproc://10.0.64.22/6973/1' processes=1 cores=8>"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cluster = LocalCluster(processes=False, local_dir= \"/g/data1a/e14/rm6294/dask-workers\")\n",
    "client = Client(cluster)\n",
    "client"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Opens Climatology and MHW SST threshold files, that have been created before.\n",
    "# Note: p stands for past, f for future\n",
    "localDir = \"/g/data1a/e14/rm6294/NOWMHW/\"\n",
    "pThresh = xr.open_dataarray(localDir + 'pastThreshRep.nc')\n",
    "pClim = xr.open_dataarray(localDir + 'pastClimRep.nc')\n",
    "fThresh = xr.open_dataarray(localDir + 'futureThreshRep.nc')\n",
    "fClim = xr.open_dataarray(localDir + 'futureClimRep.nc')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Opens NOW SST data, from which we need the SST.\n",
    "sst_dir = '/g/data1a/e14/gs9353/NOW_OUTPUTS/'\n",
    "sstFut = xr.open_zarr(sst_dir + 'now_cordex24_BMJv2_BILAP_ALL/cordex24-BMJv2_BILAP_ALL_1d_1990_2008_grid_T_2D.zarr')['tos'].sel(simulation = 'Future') #tos means sst\n",
    "sstPast = xr.open_zarr(sst_dir + 'now_cordex24_BMJv2_BILAP_old/cordex24-BMJv2_BILAP_1d_1990_2008_grid_T_2D.zarr')['tos'].sel(simulation = 'Present')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {},
   "outputs": [],
   "source": [
    "spatial_chunk = 50"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Looking for MHW\n",
    "The method we will be using to identify MHW is to:\n",
    "* Create a mask on top of the data, which has a binary True/False representing whether the sst at the location is above the corressponding threshold. \n",
    "    * Using the mask, try and find consecutive days where the threshold is crossed, as these represent the MHW.\n",
    "* Once we have all the SSTs that cross the threshold, we will the apply the duration requirement, and look for SSTs that cross the threshold for 5 consecutive days"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Creating a Mask (Crossing the threshold)\n",
    "We are looking for SST to cross the threshold. We will do this by:\n",
    "* Subtracting the background climatology from both the threshold and sst, giving us theshold anomaly (thresha) and SST anomaly (ssta).\n",
    "* Dividing ssta by thresha.\n",
    "* Saving the severity data, so we can simply call it for use in the animation section.\n",
    "This process will not only give us a matrix of threshold crosses (as ssta > thresha at this points, ssta/thresa > 1), but also tell us about the severity of the MHW, as temperatures 2 thresholds away from the background will be represented with a two in the matrix and so on."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### Note: Current looking at Future SSTs compared to a past Clim."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Finding thresha and ssta\n",
    "thresha = pThresh.chunk({'x':spatial_chunk, 'y':spatial_chunk, 'time_counter':365}) - pClim.chunk({'x':spatial_chunk, 'y':spatial_chunk, 'time_counter':365})\n",
    "ssta = sstFut.chunk({'x':spatial_chunk, 'y':spatial_chunk, 'time_counter':365}) - pClim.chunk({'x':spatial_chunk, 'y':spatial_chunk, 'time_counter':365})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Finding potential MHW events\n",
    "mhws_preDur = xr.where(ssta > thresha, ssta/thresha, 0)\n",
    "# The next line removes any points that were made very large due to epsilon error in the ssta/thresha div\n",
    "mhws_preDur = xr.where(mhws_preDur > 10, 0, mhws_preDur)\n",
    "# Below ensures that longitude coordinates go between 0 and 360. Makes plotting easier.\n",
    "mhws_preDur['nav_lon'] = mhws_preDur['nav_lon'] % 360 "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Checking for duration\n",
    "We now have all the SSTs that cross our threshold. This section will aim to find the events that meet the 5 consecutive days with at most a 2 day gap criterion. To do this we will:\n",
    "* For each the time series at each grid point, track how long each MHW occurs for.\n",
    "* Eliminate those that are less than 5 days long "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [],
   "source": [
    "def duration(severity, join_gaps = True):\n",
    "    # Finding the dates considered in severity & converting it to nanoseconds\n",
    "    mhw_dates = pd.to_numeric(severity['time_counter'])\n",
    "    # Creates mhw_dur object which has a time series (in nanoseconds) at each grid point\n",
    "    mhw_dur = xr.broadcast(severity, mhw_dates)[1]\n",
    "    mhw_dur.data = da.array.from_array(mhw_dur.data, chunks = (chunk_size, spatial_chunk, spatial_chunk))\n",
    "    \n",
    "    lbl = da.array.map_blocks(remove_false_events, mhw_dur.data, severity.data, dtype = 'float')\n",
    "    \n",
    "    return xr.where(lbl > 0, severity, 0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "def day2ns(days):\n",
    "    # Converts days to nanoseconds. Days -> Hours -> Seconds -> nanoseconds \n",
    "    return int(days * 24 * 3600 * 1e9)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "def remove_false_events(mhw_dur, severity, minDur = 5):\n",
    "    struc = np.zeros((3,3,3))\n",
    "    # Looking for consecutive SST threshold crosses for only the time dimension:\n",
    "    struc[:,1,1] = 1\n",
    "    labeled_array, num_features = ndimage.label(severity, structure = struc)   \n",
    "    indexs = da.array.arange(1, num_features + 1)\n",
    "   \n",
    "    # Calculates the max and min time points for all labeled points, i.e. the beggining and end dates for SST events \n",
    "    maxMHW = ndimage.maximum(mhw_dur, labels=labeled_array, index=indexs)\n",
    "    minMHW = ndimage.minimum(mhw_dur, labels=labeled_array, index=indexs)\n",
    "\n",
    "    # Calculates the length of all potential MHW events.\n",
    "    dur = maxMHW - minMHW + day2ns(1) \n",
    "\n",
    "    # converting minDur (default = 5) days to nanoseconds\n",
    "    minDur_ns = day2ns(minDur) \n",
    "\n",
    "    # Finds the event numbers of MHWs with duration < minDur_ns.\n",
    "    # Adding 1 so that event number matches with value in labeled_array. \n",
    "    failed_ev_num = da.array.where(dur < minDur_ns)[0]  + 1 \n",
    "    failed_ev_num = failed_ev_num.compute()\n",
    "\n",
    "    # objs has the location of each labeled event \n",
    "    # i.e objs[0] is the location of the event 1, objs[10] location of event 11 and so on.\n",
    "    objs = ndimage.find_objects(labeled_array.astype('int'))\n",
    "    \n",
    "    # failed_objs has the location for all the failed events in labeled_array \n",
    "    failed_objs = [objs[i - 1] for i in failed_ev_num]\n",
    "    # Removes all the places where we had a failed MHW\n",
    "    for loc in failed_objs:\n",
    "        labeled_array[loc] = 0\n",
    "\n",
    "    return labeled_array"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "chunk_size = 431 # <- Chunk size needs to be the same as the max spatial dimension length \n",
    "mhws_preDur = mhws_preDur.chunk({'time_counter' : chunk_size})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [],
   "source": [
    "mhw = duration(mhws_preDur)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n",
      "/g/data1/e14/rm6294/miniconda3/envs/now/lib/python3.6/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in greater\n",
      "  return func(*args2)\n"
     ]
    }
   ],
   "source": [
    "mhw = mhw.compute()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "mhw.chunk({'x' : spatial_chunk, 'y' : spatial_chunk, 'time_counter' : 365}).to_netcdf('/g/data1a/e14/rm6294/NOWMHW/severityMHWNOW_futSSTPastClim.nc')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:now]",
   "language": "python",
   "name": "conda-env-now-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
